version: '2'
services:
  database:
    container_name: mysql-docker
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: organizeit
  java:
    image: organizeit-docker
    depends_on:
      - "database"
    ports:
      - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/organizeit?useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw
      SERVER_PORT: 9090
